// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5O9VtycI1SC793e7xJBfjtenR4nuuk2Y',
    appId: '1:907523584047:web:27a9456becd254bc7956da',
    messagingSenderId: '907523584047',
    projectId: 'devopia-overload-oblivion',
    authDomain: 'devopia-overload-oblivion.firebaseapp.com',
    storageBucket: 'devopia-overload-oblivion.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxtfrJjyLTOJ5DYLEgzD2rE0dppFR5CmQ',
    appId: '1:907523584047:android:11d69a001a0dba5e7956da',
    messagingSenderId: '907523584047',
    projectId: 'devopia-overload-oblivion',
    storageBucket: 'devopia-overload-oblivion.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCePBhGUgK_0rw04x23SLXXU3-Fp_0QTC4',
    appId: '1:907523584047:ios:0bb27a2547351fd07956da',
    messagingSenderId: '907523584047',
    projectId: 'devopia-overload-oblivion',
    storageBucket: 'devopia-overload-oblivion.appspot.com',
    iosBundleId: 'com.example.devopiaOverloadOblivion',
  );
}
